### ISSUE TITLE
click on a contact and show contacts from Domain Address Book

### ISSUE THREAD

**Issue by vmalaga** [t3chguy/Roundcube-SQL-Global-Address-Books#11]
Hi

I would like to use yours address book with my iredmail-roundcube installation, but i have find any problems.

When i am at the contacts tab and try to click on any contact, some can be clicked and showed, but other can't be clicked so i can't see the contact informattion

The autocomplete feature works fine

![addressbook](https://cloud.githubusercontent.com/assets/500904/6767635/e7d39dec-d03a-11e4-9327-10a71fac21f1.png)

versions:
iredmail 0.9
roundcube 1.1.0

**Comment by t3chguy** [comment]
This issue is most likely due to a weird cell in the mailbox table, could you take a look at your MySQL View and if there are any "NULL" inside the ID Column, then those are the ones you can't see. This is due to an issue in newer MySQL Version which happens if a user hasn't changed his password and hasn't been modified in iRedMail. I have just fixed this, all you have to do is update the MySQL View with the new one. Let me know if this works for you.

**Comment by vmalaga** [comment]
The vmail.mailbox.created field is `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00'  and i have any rows with 0000-00-00 00:00:00 values on create, I don't know why, but it return NULL ID on the view

I think that if vmail.mailbox username is the PRIMARY KEY a hashing function like md5(username) give you an uniqueid for the view, i have test it and return allways and ID with the view

CREATE
    ALGORITHM = UNDEFINED
        DEFINER = `root`@`localhost`
            SQL SECURITY DEFINER
            VIEW `global_addressbook` AS

SELECT
        md5(`vmail`.`mailbox`.`username`) AS `ID`,
        `vmail`.`mailbox`.`name` AS `name`,
        `vmail`.`mailbox`.`username` AS `email`,
        `vmail`.`mailbox`.`domain` AS `domain`
FROM
        `vmail`.`mailbox`;

**Comment by t3chguy** [comment]
While yes that works, and is fine, Roundcube suggests using numeric IDs so I was using a Numeric form just in-case they choose to enforce that in a future version. If this works for you then great, I'll query the Roundcube Devs to check whether String IDs are alright in the long-term

**Comment by vmalaga** [comment]
i will take a look at the repo for future changes
thank

**Comment by t3chguy** [comment]
All I'm sure of is that some symbols in the ID break the Address Book functionality even more, since md5 and sha1 are Binary represented in Hexadecimal it should be fine. If not you could always run a Hex=>Dec conversion on it, lessening the entropy. The only "PERFECT" way I can think of is if the iRedMail table ships/or is modified to have an AI PK [Auto-Incremental Primary-Key]
If you have any suggestions for the books just please let me know and i'll see what I can do!
Thanks for your interest

**Comment by vmalaga** [comment]
I'm testing it and for now i have not see any issue, 
now i only have 40 accounts, but tomorrow I will do the migration of 6,000 counts over 700 domains and hope that the performance is good

best regards

**Comment by t3chguy** [comment]
The code itself is lighter than the built in Contacts code, the only bit that may weigh it down is the MySQL View
Let me know how it works for you after the migration, hope well
