### ISSUE TITLE
Improper indent in config.inc.php.dist

### ISSUE THREAD

**Issue by ghost** [t3chguy/Roundcube-SQL-Global-Address-Books#2]
``` php
//e.g:                                   = 'Domain Book';
        $config['_sql_domainbook_name']  = 'Domain Book';

//READ Allowed is the list of domains (or *) which can see this Address Book.
        //$config['_sql_db_read_allowed']  = array('*');
...
```

**Comment by ghost** [comment]
By the way, is it better to use `Domain Address Book` instead of `Domain Book`?

**Comment by t3chguy** [comment]
I'll change them to one tab but if you read the first few lines,

```
//By Default The DomainBook is Enabled and Shown to ALL Individually! All Configuration Options are Tabbed.
```

I tabbed them just so they stand out from the comments, otherwise they're a little hard to see.
And I'll change the default to `Domain Address Book` as it seems more generic, but its just the name of the Book in your Roundcube Address Book, so it can be any string.

**Comment by t3chguy** [comment]
@zhanghuangbin Just pushed a new config, conforms to standard single tabbing and also uses `/* for Comments */` and `//For disabled configuration options` to help differentiate them without the double tabbing. Let me know what you think!
